export function htmlDocument(sceneMarkup: string, scene: { warnings?: string[]; view?: string }) {
  const data = JSON.stringify(scene).replace(/</g, "\\u003c");
  const warnings = Array.isArray(scene.warnings)
    ? scene.warnings.map((warning) => `<p class="warning">${warning.replace(/&/g, "&amp;").replace(/</g, "&lt;")}</p>`).join("")
    : "";
  const warningBlock = warnings ? `<div class="warnings" role="status">${warnings}</div>` : "";
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mise en Scene export</title><style>body{margin:0;background:#0d1014;color:#dde3ea;font:15px system-ui}main{max-width:1280px;margin:auto;padding:24px}.views button{margin:0 8px 12px 0;padding:8px 12px}.view[hidden]{display:none}.inspector{padding:12px;border:1px solid #2a323d}.warnings{margin:0 0 16px;padding:12px 14px;border:1px solid #5c3d1e;border-radius:8px;background:#1a140d}.warnings .warning{margin:0;color:#e0a45c}.warnings .warning+.warning{margin-top:8px}svg{width:100%;height:auto}</style></head><body><main><div class="views"><button data-view="architecture">Architecture</button><button data-view="sequence">Sequence</button></div>${warningBlock}${sceneMarkup}<p class="inspector" aria-live="polite">Select an element to inspect it.</p><script type="application/json" id="scene-data">${data}</script><script>(()=>{const d=JSON.parse(document.querySelector('#scene-data').textContent);const show=v=>document.querySelectorAll('.view').forEach(x=>x.hidden=x.dataset.view!==v);document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));document.querySelectorAll('[data-block-id],[data-edge-id]').forEach(n=>{n.tabIndex=0;const pick=()=>{const item=d.blocks.find(x=>x.id===n.dataset.blockId)||d.edges.find(x=>x.id===n.dataset.edgeId);document.querySelector('.inspector').textContent=item?item.label:'Unknown element'};n.addEventListener('click',pick);n.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pick()}})});show(d.view)})();</script></main></body></html>`;
}

export function svgDocument(markup: string) {
  return markup.replace(/^<svg/, '<svg xmlns="http://www.w3.org/2000/svg"').replace(/<script[\s\S]*?<\/script>/gi, "");
}

// Self-contained animated walkthrough. Each step carries element IDs, a caption,
// and a camera transform; the inline controller toggles spotlight classes and
// eases the camera group between steps. It evaluates no imported strings and
// injects no HTML.
export function walkthroughHtml(sceneMarkup: string, steps: unknown) {
  const data = JSON.stringify(steps).replace(/</g, "\\u003c");
  const style = `body{margin:0;background:radial-gradient(120% 90% at 50% 0%,#141b24 0%,#0d1014 60%);color:#dde3ea;font:15px system-ui}main{max-width:1280px;margin:auto;padding:24px}.walk-stage{position:relative;border:1px solid #1e242c;border-radius:12px;overflow:hidden}svg{width:100%;height:auto;display:block}.walk-title{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:24px;background:linear-gradient(180deg,rgba(13,16,20,.55),rgba(13,16,20,.78));opacity:0;pointer-events:none;transition:opacity .5s ease}.walk-title.show{opacity:1}.walk-title h1{margin:0 0 10px;font-size:34px;font-weight:700;letter-spacing:-.02em}.walk-title p{margin:0;font-family:ui-monospace,Menlo,Consolas,monospace;font-size:12px;letter-spacing:.14em;text-transform:uppercase;color:#e0a45c}.walk-progress{height:3px;margin-top:12px;background:#1e242c;border-radius:2px;overflow:hidden}#walk-fill{display:block;height:100%;width:0;background:#e0a45c;transition:width .4s ease}.walk-bar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:12px}.walk-bar button{padding:8px 14px;background:#11161c;color:#dde3ea;border:1px solid #2a323d;border-radius:8px;cursor:pointer;font:inherit}.walk-bar button:hover,.walk-bar button:focus-visible{border-color:#4a5664}#walk-caption{font-family:ui-monospace,Menlo,Consolas,monospace;font-size:13px;color:#e0a45c}#walk-counter{margin-left:auto;color:#9aa4b2;font-size:13px}`;
  const script = `(()=>{var steps=JSON.parse(document.getElementById('walk-steps').textContent);if(!steps.length)return;var cap=document.getElementById('walk-caption'),cnt=document.getElementById('walk-counter'),fill=document.getElementById('walk-fill'),play=document.getElementById('walk-play'),title=document.getElementById('walk-title'),cam=document.querySelector('.stage-camera');var blocks=[].slice.call(document.querySelectorAll('[data-block-id]')),edges=[].slice.call(document.querySelectorAll('[data-edge-id]'));var reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;var i=0,timer=null,raf=null,curr={x:0,y:0,s:1};function pc(t){var m=/translate\\(([-0-9.]+) ([-0-9.]+)\\) scale\\(([-0-9.]+)\\)/.exec(t||'');return m?{x:+m[1],y:+m[2],s:+m[3]}:{x:0,y:0,s:1}}function apply(c){if(cam)cam.setAttribute('transform','translate('+c.x.toFixed(1)+' '+c.y.toFixed(1)+') scale('+c.s.toFixed(3)+')')}function ease(t){return t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2}function moveTo(t){var target=pc(t);if(reduce||!cam){curr=target;apply(curr);return}if(raf)cancelAnimationFrame(raf);var from={x:curr.x,y:curr.y,s:curr.s},start=null;function frame(ts){if(start===null)start=ts;var p=Math.min(1,(ts-start)/650),e=ease(p);curr={x:from.x+(target.x-from.x)*e,y:from.y+(target.y-from.y)*e,s:from.s+(target.s-from.s)*e};apply(curr);if(p<1)raf=requestAnimationFrame(frame)}raf=requestAnimationFrame(frame)}var set=function(n,a){n.classList.remove('walk-on','walk-dim');n.classList.add(a?'walk-on':'walk-dim')},clr=function(n){n.classList.remove('walk-on','walk-dim')};function paint(){var s=steps[i];if(s.edgeId===null){blocks.forEach(clr);edges.forEach(clr)}else{var on={};(s.blockIds||[]).forEach(function(id){on[id]=1});blocks.forEach(function(n){set(n,!!on[n.getAttribute('data-block-id')])});edges.forEach(function(n){set(n,n.getAttribute('data-edge-id')===s.edgeId)})}moveTo(s.camera);cap.textContent=s.caption;cnt.textContent=(i+1)+' / '+steps.length;fill.style.width=((i+1)/steps.length*100)+'%';if(title)title.classList.toggle('show',i===0)}function go(n){i=(n%steps.length+steps.length)%steps.length;paint()}function stop(){if(timer){clearInterval(timer);timer=null}play.textContent='Play'}function start(){stop();timer=setInterval(function(){go(i+1)},2200);play.textContent='Pause'}play.addEventListener('click',function(){timer?stop():start()});document.getElementById('walk-prev').addEventListener('click',function(){stop();go(i-1)});document.getElementById('walk-next').addEventListener('click',function(){stop();go(i+1)});var rels=steps.length-1;if(title)title.innerHTML='<h1></h1><p></p>';if(title){title.querySelector('h1').textContent=steps[0].caption;title.querySelector('p').textContent=rels+(rels===1?' relationship':' relationships')+' \\u00b7 press Play'}paint();start()})();`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mise en Scene walkthrough</title><style>${style}</style></head><body><main><div class="walk-stage">${sceneMarkup}<div class="walk-title" id="walk-title"></div></div><div class="walk-progress"><span id="walk-fill"></span></div><div class="walk-bar"><button id="walk-play" type="button">Pause</button><button id="walk-prev" type="button">Prev</button><button id="walk-next" type="button">Next</button><span id="walk-caption" aria-live="polite"></span><span id="walk-counter"></span></div><script type="application/json" id="walk-steps">${data}</script><script>${script}</script></main></body></html>`;
}
