export function htmlDocument(sceneMarkup: string, scene: unknown) {
  const data = JSON.stringify(scene).replace(/</g, "\\u003c");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mise en Scene export</title><style>body{margin:0;background:#0d1014;color:#dde3ea;font:15px system-ui}main{max-width:1280px;margin:auto;padding:24px}.views button{margin:0 8px 12px 0;padding:8px 12px}.view[hidden]{display:none}.inspector{padding:12px;border:1px solid #2a323d}svg{width:100%;height:auto}</style></head><body><main><div class="views"><button data-view="architecture">Architecture</button><button data-view="sequence">Sequence</button></div>${sceneMarkup}<p class="inspector" aria-live="polite">Select an element to inspect it.</p><script type="application/json" id="scene-data">${data}</script><script>(()=>{const d=JSON.parse(document.querySelector('#scene-data').textContent);const show=v=>document.querySelectorAll('.view').forEach(x=>x.hidden=x.dataset.view!==v);document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));document.querySelectorAll('[data-block-id],[data-edge-id]').forEach(n=>{n.tabIndex=0;const pick=()=>{const item=d.blocks.find(x=>x.id===n.dataset.blockId)||d.edges.find(x=>x.id===n.dataset.edgeId);document.querySelector('.inspector').textContent=item?item.label:'Unknown element'};n.addEventListener('click',pick);n.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pick()}})});show(d.view)})();</script></main></body></html>`;
}

export function svgDocument(markup: string) {
  return markup.replace(/^<svg/, '<svg xmlns="http://www.w3.org/2000/svg"').replace(/<script[\s\S]*?<\/script>/gi, "");
}

// Self-contained animated walkthrough. The steps array carries only element IDs
// and captions; the inline controller toggles spotlight classes on the already
// rendered SVG. It evaluates no imported strings and injects no HTML.
export function walkthroughHtml(sceneMarkup: string, steps: unknown) {
  const data = JSON.stringify(steps).replace(/</g, "\\u003c");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mise en Scene walkthrough</title><style>body{margin:0;background:#0d1014;color:#dde3ea;font:15px system-ui}main{max-width:1280px;margin:auto;padding:24px}svg{width:100%;height:auto}.walk-bar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:12px}.walk-bar button{padding:8px 14px;background:#11161c;color:#dde3ea;border:1px solid #2a323d;border-radius:8px;cursor:pointer}.walk-bar button:hover{border-color:#4a5664}#walk-caption{font-family:ui-monospace,Menlo,Consolas,monospace;font-size:13px;color:#e0a45c}#walk-counter{margin-left:auto;color:#9aa4b2;font-size:13px}</style></head><body><main><div class="stage">${sceneMarkup}</div><div class="walk-bar"><button id="walk-play" type="button">Pause</button><button id="walk-prev" type="button">Prev</button><button id="walk-next" type="button">Next</button><span id="walk-caption" aria-live="polite"></span><span id="walk-counter"></span></div><script type="application/json" id="walk-steps">${data}</script><script>(()=>{const steps=JSON.parse(document.getElementById('walk-steps').textContent);if(!steps.length)return;const cap=document.getElementById('walk-caption'),cnt=document.getElementById('walk-counter'),play=document.getElementById('walk-play');const blocks=[...document.querySelectorAll('[data-block-id]')],edges=[...document.querySelectorAll('[data-edge-id]')];let i=0,timer=null;const set=(n,a)=>{n.classList.remove('walk-on','walk-dim');n.classList.add(a?'walk-on':'walk-dim')};const clr=n=>n.classList.remove('walk-on','walk-dim');function paint(){const s=steps[i];if(s.edgeId===null){blocks.forEach(clr);edges.forEach(clr)}else{const on=new Set(s.blockIds||[]);blocks.forEach(n=>set(n,on.has(n.getAttribute('data-block-id'))));edges.forEach(n=>set(n,n.getAttribute('data-edge-id')===s.edgeId))}cap.textContent=s.caption;cnt.textContent=(i+1)+' / '+steps.length}function go(n){i=(n%steps.length+steps.length)%steps.length;paint()}function stop(){if(timer){clearInterval(timer);timer=null}play.textContent='Play'}function start(){stop();timer=setInterval(()=>go(i+1),1800);play.textContent='Pause'}play.addEventListener('click',()=>timer?stop():start());document.getElementById('walk-prev').addEventListener('click',()=>{stop();go(i-1)});document.getElementById('walk-next').addEventListener('click',()=>{stop();go(i+1)});paint();start()})();</script></main></body></html>`;
}
